spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        app-id-uri: ${APP_URI}
        authorization-clients:
          accountManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${ACCOUNT_MANAGEMENT_AZ_API}/.default
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
  jpa:
    hibernate:
      # Set to update for functional tests, so it creates the environment in H2
      ddl-auto: update
ervice-to-service:
  account-management: ${ACCOUNT_MANAGEMENT_URL:https://pip-account-management.staging.platform.hmcts.net/}
dbMigration:
  runOnStartup: true
