java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DB_HOST: "{{ .Release.Name }}-postgresql"
    DB_NAME: "{{ .Values.postgresql.auth.database}}"
    DB_USER: "{{ .Values.postgresql.auth.username}}"
    DB_PASS: "{{ .Values.postgresql.auth.password}}"
    DB_PORT: "5432"
  disableKeyVaults: true
  postgresql:
    enabled: true
