java:
  applicationPort: 4550
  image: 'sdshmctspublic.azurecr.io/pip/subscription-management:latest'
  ingressHost: pip-subscription-management.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: pip
  keyVaults:
    pip-ss-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: subscription-management-POSTGRES-DATABASE
          alias: DB_NAME
        - name: subscription-management-POSTGRES-PASS
          alias: DB_PASS
        - name: subscription-management-POSTGRES-PORT
          alias: DB_PORT
        - name: subscription-management-POSTGRES-USER
          alias: DB_USER
        - name: subscription-management-POSTGRES-HOST
          alias: DB_HOST
  environment:
